export const factoryABI = [
  {
    name: "createRing",
    type: "function",
    stateMutability: "nonpayable",
    inputs: [
      { name: "_stakeAmount", type: "uint256" },
      { name: "_epochDuration", type: "uint256" },
      { name: "_liquidationGracePeriod", type: "uint256" },
      { name: "_minParticipants", type: "uint256" },
      { name: "_maxParticipants", type: "uint256" },
      { name: "_bountyBps", type: "uint256" },
    ],
    outputs: [{ name: "ring", type: "address" }],
  },
  {
    name: "totalRings",
    type: "function",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "uint256" }],
  },
  {
    name: "getAllRings",
    type: "function",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "address[]" }],
  },
  {
    name: "getRings",
    type: "function",
    stateMutability: "view",
    inputs: [
      { name: "offset", type: "uint256" },
      { name: "limit", type: "uint256" },
    ],
    outputs: [{ name: "result", type: "address[]" }],
  },
  {
    name: "getRingsByCreator",
    type: "function",
    stateMutability: "view",
    inputs: [{ name: "creator", type: "address" }],
    outputs: [{ name: "", type: "address[]" }],
  },
  {
    name: "isRing",
    type: "function",
    stateMutability: "view",
    inputs: [{ name: "", type: "address" }],
    outputs: [{ name: "", type: "bool" }],
  },
  {
    name: "RingCreated",
    type: "event",
    inputs: [
      { name: "ring", type: "address", indexed: true },
      { name: "creator", type: "address", indexed: true },
      { name: "stakeAmount", type: "uint256", indexed: false },
      { name: "epochDuration", type: "uint256", indexed: false },
      {
        name: "liquidationGracePeriod",
        type: "uint256",
        indexed: false,
      },
      { name: "minParticipants", type: "uint256", indexed: false },
      { name: "maxParticipants", type: "uint256", indexed: false },
      { name: "bountyBps", type: "uint256", indexed: false },
    ],
  },
] as const;

export const heartbeatRingABI = [
  {
    name: "phase",
    type: "function",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "uint8" }],
  },
  {
    name: "stakeAmount",
    type: "function",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "uint256" }],
  },
  {
    name: "ringHead",
    type: "function",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "address" }],
  },
  {
    name: "epochDuration",
    type: "function",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "uint256" }],
  },
  {
    name: "liquidationGracePeriod",
    type: "function",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "uint256" }],
  },
  {
    name: "ringSize",
    type: "function",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "uint256" }],
  },
  {
    name: "totalParticipants",
    type: "function",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "uint256" }],
  },
  {
    name: "currentEpoch",
    type: "function",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "uint256" }],
  },
  {
    name: "timeUntilEpochEnd",
    type: "function",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "uint256" }],
  },
  {
    name: "isDelinquent",
    type: "function",
    stateMutability: "view",
    inputs: [{ name: "who", type: "address" }],
    outputs: [{ name: "", type: "bool" }],
  },
  {
    name: "getRing",
    type: "function",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "addrs", type: "address[]" }],
  },
  {
    name: "participants",
    type: "function",
    stateMutability: "view",
    inputs: [{ name: "", type: "address" }],
    outputs: [
      { name: "next", type: "address" },
      { name: "prev", type: "address" },
      { name: "stake", type: "uint128" },
      { name: "lastBeat", type: "uint64" },
      { name: "alive", type: "bool" },
    ],
  },
  {
    name: "gameStartTime",
    type: "function",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "uint256" }],
  },
  {
    name: "minParticipants",
    type: "function",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "uint256" }],
  },
  {
    name: "maxParticipants",
    type: "function",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "uint256" }],
  },
  {
    name: "liquidationBountyBps",
    type: "function",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "uint256" }],
  },
  {
    name: "creator",
    type: "function",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "address" }],
  },
  {
    name: "registrationDeadline",
    type: "function",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "uint256" }],
  },
  {
    name: "pendingBounties",
    type: "function",
    stateMutability: "view",
    inputs: [{ name: "", type: "address" }],
    outputs: [{ name: "", type: "uint256" }],
  },
  {
    name: "register",
    type: "function",
    stateMutability: "payable",
    inputs: [],
    outputs: [],
  },
  {
    name: "startGame",
    type: "function",
    stateMutability: "nonpayable",
    inputs: [],
    outputs: [],
  },
  {
    name: "heartbeat",
    type: "function",
    stateMutability: "nonpayable",
    inputs: [],
    outputs: [],
  },
  {
    name: "liquidate",
    type: "function",
    stateMutability: "nonpayable",
    inputs: [{ name: "target", type: "address" }],
    outputs: [],
  },
  {
    name: "claim",
    type: "function",
    stateMutability: "nonpayable",
    inputs: [],
    outputs: [],
  },
  {
    name: "withdrawBounty",
    type: "function",
    stateMutability: "nonpayable",
    inputs: [],
    outputs: [],
  },
  {
    name: "refundRegistration",
    type: "function",
    stateMutability: "nonpayable",
    inputs: [],
    outputs: [],
  },
  {
    name: "Registered",
    type: "event",
    inputs: [
      { name: "participant", type: "address", indexed: true },
      { name: "position", type: "uint256", indexed: false },
    ],
  },
  {
    name: "RegistrationRefunded",
    type: "event",
    inputs: [
      { name: "participant", type: "address", indexed: true },
      { name: "amount", type: "uint256", indexed: false },
    ],
  },
  {
    name: "RingFormed",
    type: "event",
    inputs: [
      { name: "participants", type: "uint256", indexed: false },
      { name: "epochDuration", type: "uint256", indexed: false },
    ],
  },
  {
    name: "Heartbeat",
    type: "event",
    inputs: [
      { name: "participant", type: "address", indexed: true },
      { name: "epoch", type: "uint256", indexed: true },
    ],
  },
  {
    name: "Liquidated",
    type: "event",
    inputs: [
      { name: "target", type: "address", indexed: true },
      { name: "leftBeneficiary", type: "address", indexed: true },
      { name: "rightBeneficiary", type: "address", indexed: true },
      { name: "leftShare", type: "uint256", indexed: false },
      { name: "rightShare", type: "uint256", indexed: false },
      { name: "bounty", type: "uint256", indexed: false },
      { name: "epoch", type: "uint256", indexed: false },
    ],
  },
  {
    name: "RingRelinked",
    type: "event",
    inputs: [
      { name: "newLeft", type: "address", indexed: false },
      { name: "newRight", type: "address", indexed: false },
      { name: "ringSize", type: "uint256", indexed: false },
    ],
  },
  {
    name: "GameOver",
    type: "event",
    inputs: [
      { name: "survivors", type: "uint256", indexed: false },
      { name: "totalPool", type: "uint256", indexed: false },
    ],
  },
  {
    name: "Claimed",
    type: "event",
    inputs: [
      { name: "survivor", type: "address", indexed: true },
      { name: "amount", type: "uint256", indexed: false },
    ],
  },
  {
    name: "BountyAccrued",
    type: "event",
    inputs: [
      { name: "liquidator", type: "address", indexed: true },
      { name: "amount", type: "uint256", indexed: false },
    ],
  },
  {
    name: "BountyWithdrawn",
    type: "event",
    inputs: [
      { name: "liquidator", type: "address", indexed: true },
      { name: "amount", type: "uint256", indexed: false },
    ],
  },
  {
    name: "Initialized",
    type: "event",
    inputs: [
      { name: "creator", type: "address", indexed: true },
      { name: "stakeAmount", type: "uint256", indexed: false },
      { name: "epochDuration", type: "uint256", indexed: false },
      {
        name: "liquidationGracePeriod",
        type: "uint256",
        indexed: false,
      },
      { name: "minParticipants", type: "uint256", indexed: false },
      { name: "maxParticipants", type: "uint256", indexed: false },
      { name: "bountyBps", type: "uint256", indexed: false },
      { name: "registrationDeadline", type: "uint256", indexed: false },
    ],
  },
] as const;
